# Generated by Django 5.0.2 on 2024-02-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_do_produto', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('preco_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atacado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ipi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apoi01', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apoio02', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagina', models.IntegerField()),
            ],
        ),
    ]
