# Generated by Django 5.0.3 on 2024-03-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_remove_produto_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='ipi',
        ),
    ]
