# Generated by Django 5.0.3 on 2025-08-22 15:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(db_index=True, max_length=20)),
                ('statement_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FUTURE', 'FUTURE'), ('CLOSED_NOT_DUE', 'CLOSED_NOT_DUE')], max_length=20)),
                ('cycle', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cycle_closing_at', models.DateField()),
                ('due_at', models.DateField()),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('debits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid_until_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount_paid_after_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_credits_until_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_credits_after_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('evolve_to_delinquency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['account_id', 'due_at'], name='faturas_fat_account_410a11_idx'), models.Index(fields=['status'], name='faturas_fat_status_7ddef1_idx')],
            },
        ),
    ]
